# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e59269d755ec6ff6de726f874174a672ee11b6c291c870692beca3b88703c6a05298f57be2cc82fdcedc3e42e7b3d0221c6dcd1c99a0470d2f5276135be2d6

test:
  secret_key_base: 6184ddc32bd8d802011b895c52acd64bed3ea39b4f320b2ef2fe09b7c06f5aa88542a914d0634c02cabc6511dc5357cb9dd59be4555ba5ee8fd3bc2376f94918

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
